site_name: Portfolio
site_author: Mateusz Wilczewski
site_url: https://mateusz-93.github.io/ai_portfolio
site_description: >-
    Portfolio moich projektów z Data Science i AI!

repo_name: Mateusz-93/ai_portfolio
repo_url: https://github.com/Mateusz-93/ai_portfolio


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      toggle:
        icon: material/weather-night
        name: Przełącz na tryb ciemny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      toggle:
        icon: material/weather-sunny
        name: Przełącz na tryb jasny

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "MrEchoScribe": mr_echoscribe/index.md
- Poprzednie projekty:
  - "Titanic": titanic/index.md
  - "Iris": iris/index.md
  - "Pencil Master": kolorowanka/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mateusz-93
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:mateuszvvilczewski@gmail.com
      name: Email